version: "3"
services:
  #www:
  #  image: "gabrielmilan/www-lps:main-4.0"
  #  volumes:
  #    - /mnt/homes:/home
  #  ports:
  #    - "80:80"
  #  restart: unless-stopped
  #  container_name: www

  redirect_site:
    image: morbz/docker-web-redirect
    restart: always
    environment:
      - VIRTUAL_HOST=lps.ufrj.br
      - REDIRECT_TARGET=https://sites.google.com/lps.ufrj.br/lps/in√≠cio
    ports:
      - "80:80"

  redirect_gitlab:
    image: morbz/docker-web-redirect
    restart: always
    environment:
      - VIRTUAL_HOST=gitlab.lps.ufrj.br
      - REDIRECT_TARGET=https://gitlab.com/lps.ufrj.br
    ports:
      - "81:80"

  #paf:
  #  image: "gabrielmilan/www-lps:paf-4.0"
  #  ports:
  #    - "81:80"
  #  restart: unless-stopped
  #  container_name: paf


  #virtuais:
  #  image: "gabrielmilan/www-lps:virtuais-4.0"
  #  volumes:
  #    - /mnt/homes:/home
  #  ports:
  #    - "82:80"
  #  restart: unless-stopped
  #  container_name: virtuais




